dist: focal
language: python
python:
  - 3.11
install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - coverage run --source=. mysite/manage.py test polls

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_ID"
  secret_access_key: "$AWS_SECRET_KEY"
  region: "us-west-2"
  app: "hw2-app"
  env: "hw2-app-env"
  bucket_name: "elasticbeanstalk-us-west-2-509399599475"
  on:
    branch: main
